package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * ChangeEmailMobile generated by hbm2java
 */
@Entity
@Table(name = "change_email_mobile", catalog = "db_allure")
@Getter
@Setter
public class ChangeEmailMobile extends AuditableBaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	private Users users;

	@Column(name = "change_type", nullable = false)
	private byte changeType;
	
	@Column(name = "change_value", nullable = false, length = 100)
	private String changeValue;
	
	@Column(name = "otp", nullable = false, length = 45)
	private String otp;
	
	@Column(name = "otp_attempts", nullable = false)
	private byte otpAttempts;
	
	@Column(name = "status", nullable = false)
	private byte status;

}
