package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * PreferAddiction generated by hbm2java
 */
@Entity
@Table(name = "email_log", catalog = "db_allure")
@Getter
@Setter
public class EmailLog extends AuditableBaseEntity implements java.io.Serializable {

	@Column(name = "user_id", nullable = false)
	private int userId;

	@Column(name = "email_type", nullable = false)
	private String emailType;

	@Column(name = "user_email", nullable = false)
	private String userEmail;
	
	@Column(name = "status", nullable = false)
	private Boolean status;
	
	@Column(name = "message", nullable = false)
	private String message;
	
}
