package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.Getter;
import lombok.Setter;

/**
 * FeedList generated by hbm2java
 */
@Entity
@Table(name = "feed_list", catalog = "db_allure", uniqueConstraints = @UniqueConstraint(columnNames = { "user_id",
		"profile_id", "feed_type", "value" }))
@Getter
@Setter
public class FeedList extends AuditableBaseEntity implements java.io.Serializable {

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", insertable = false, updatable = false)
	private Users usersByUserId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_id", insertable = false, updatable = false)
	private Users usersByProfileId;

	@Column(name = "feed_type", nullable = false)
	private byte feedType;
	
	@Column(name = "value", length = 45)
	private String value;
	
}
