package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * ForgetPassword generated by hbm2java
 */
@Entity
@Table(name = "forget_password", catalog = "db_allure")
@Getter
@Setter
public class ForgetPassword extends AuditableBaseEntity implements java.io.Serializable {

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	private Users users;
	
	@Column(name = "otp", nullable = false)	
	private int otp;
	
	@Column(name = "otp_attempts", nullable = false)
	private byte otpAttempts;
	
	@Column(name = "status", nullable = false)
	private byte status;
}
