package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.Getter;
import lombok.Setter;

/**
 * ListBodyType generated by hbm2java
 */
@Entity
@Table(name = "list_body_type", catalog = "db_allure", uniqueConstraints = @UniqueConstraint(columnNames = "value"))
@Getter
@Setter
public class ListBodyType extends BaseEntity implements java.io.Serializable {

	@Column(name = "value", unique = true, nullable = false, length = 45)
	private String value;
}
