package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * ListDrinkingHabit generated by hbm2java
 */
@Entity
@Table(name = "list_drinking_habit", catalog = "db_allure")
@Getter
@Setter
public class ListDrinkingHabit extends BaseEntity implements java.io.Serializable {

	@Column(name = "value", nullable = false, length = 45)
	private String value;

}
