package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * ProfileLikeDislike generated by hbm2java
 */
@Entity
@Table(name = "matches", catalog = "db_allure")
@Getter
@Setter
public class Matches extends AuditableBaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = -5132102452190558377L;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	private Users usersByUserId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_id", nullable = false)
	private Users usersByProfileId;

}
