package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Where;

import lombok.Getter;
import lombok.Setter;

/**
 * PassionCategories generated by hbm2java
 */
@Entity
@Table(name = "passion_categories", catalog = "db_allure")
@Getter
@Setter
public class PassionCategories extends BaseEntity implements java.io.Serializable {

	@Column(name = "passion_category", nullable = false)
	private String passionCategory;

	@Column(name = "is_deleted", nullable = false)
	private boolean isDeleted;

	@OneToMany(fetch=FetchType.LAZY, mappedBy="passionCategories")
	@Where(clause = "is_deleted=false")
	private List<Passions> passions;
}
