package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * PreferAddiction generated by hbm2java
 */
@Entity
@Table(name = "prefer_addiction", catalog = "db_allure")
@Getter
@Setter
public class PreferAddiction extends BaseEntity implements java.io.Serializable {

	@Column(name = "user_id", nullable = false)
	private int userId;

	@Column(name = "addiction_id", nullable = false)
	private int addictionId;
	
}
