package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import lombok.Getter;
import lombok.Setter;

/**
 * ProfileLikeDislike generated by hbm2java
 */
@Entity
@Table(name = "profile_like_dislike", catalog = "db_allure", uniqueConstraints = @UniqueConstraint(columnNames = {
		"user_id", "profile_id" }))
@Getter
@Setter
public class ProfileLikeDislike extends AuditableBaseEntity implements java.io.Serializable {


	private static final long serialVersionUID = -1745986254184814278L;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_id", nullable = false)
	private Users usersByProfileId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	private Users usersByUserId;

	@Column(name = "like_status", nullable = false, length = 2)
	private String likeStatus;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedAt", length = 19)
	private Date updatedAt;

}
