package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * SexualOrientations generated by hbm2java
 */
@Entity
@Table(name = "sexual_orientations", catalog = "db_allure")
@Getter
@Setter
public class SexualOrientations extends BaseEntity implements java.io.Serializable {

	@Column(name = "sexual_orientaion", nullable = false)
	private String sexualOrientaion;

	@Column(name = "is_deleted", nullable = false)
	private boolean isDeleted;
	
}
