package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * SupportQuestion generated by hbm2java
 */
@Entity
@Table(name = "support_question", catalog = "db_allure")
@Getter
@Setter
public class SupportQuestion extends BaseEntity implements java.io.Serializable {

	@Column(name = "user_id", nullable = false)
	private int userId;

	@Column(name = "question", nullable = false, length = 500)
	private String question;
	
	@Column(name = "attachment_key", length = 100)
	private String attachmentKey;
	
	@Column(name = "email", length = 45)
	private String email;

}
