package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Getter;
import lombok.Setter;

/**
 * UserSexualOrientations generated by hbm2java
 */
@Entity
@Table(name = "user_sexual_orientations", catalog = "db_allure")
@Getter
@Setter
public class UserSexualOrientations extends AuditableBaseEntity implements java.io.Serializable {

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sexual_orientation_id")
	private SexualOrientations sexualOrientations;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id")
	private Users users;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedAt", length = 19)
	private Date updatedAt;

}
