package com.allure.entity;
// Generated 23 Oct, 2021 7:48:14 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Getter;
import lombok.Setter;

/**
 * UserPurchasedPlans generated by hbm2java
 */
@Entity
@Table(name = "user_purchased_plans", catalog = "db_allure")
@Getter
@Setter
public class UserPurchasedPlans extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = -3016073370728438433L;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_structure_id", nullable = false)
	private PlanPaymentStructures planPaymentStructures;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plan_id", nullable = false)
	private Plans plans;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	private Users users;

	@Column(name = "transaction_id", nullable = false)
	private String transactionId;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transaction_on", nullable = false, length = 19)
	private Date transactionOn;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "validtill", length = 19)
	private Date validtill;

	@Column(name = "is_success", nullable = false)
	private Boolean isSuccess;

}
