package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * UserPassions generated by hbm2java
 */
@Entity
@Table(name = "user_passions", catalog = "db_allure")
@Getter
@Setter
public class UserPassions extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = -1620938595978939902L;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "passion_id")
	private Passions passions;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	private Users users;

}
