package com.allure.entity;
// Generated 18 Sep, 2021 10:44:47 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Getter;
import lombok.Setter;

/**
 * UserSetting generated by hbm2java
 */
@Entity
@Table(name = "user_setting", catalog = "db_allure")
@Getter
@Setter
public class UserSetting implements java.io.Serializable {


	private static final long serialVersionUID = -4894256009794485725L;

	@GenericGenerator(name = "com.allure.entity.UserSettingIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "users"))
	@Id
	@GeneratedValue(generator = "com.allure.entity.UserSettingIdGenerator")

	@Column(name = "user_id", unique = true, nullable = false)
	private int userId;

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Users users;
	
	@Column(name = "topPicks")
	private Byte topPicks;

	@Column(name = "showMeOnline")
	private Byte showMeOnline;

	@Column(name = "readReceipt")
	private Byte readReceipt;

	@Column(name = "activityStatus")
	private Byte activityStatus;

	@Column(name = "showMe")
	private Byte showMe;

	@Column(name = "hereTo")
	private Byte hereTo;

	@Column(name = "minAge")
	private Byte minAge;

	@Column(name = "maxAge")
	private Byte maxAge;

	@Column(name = "distanceUnit")
	private Byte distanceUnit;

	@Column(name = "maxDistance")
	private Integer maxDistance;

	@Column(name = "prefer_clean_months")
	private Integer preferCleanMonths;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	private Date createdAt;

}
